# Generated by Django 3.0.5 on 2020-05-30 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essentials_kit_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='cost_per_item',
            new_name='price_per_item',
        ),
    ]
